### ISSUE TITLE
possible bug with scale continuous min/maxvalue

### ISSUE THREAD

**Issue by skariel** [dcjones/Gadfly.jl#280]
viewport is not limited to given values when data is outside of values. 

reproduce like this:

```plot(x=rand(10), y=rand(10), Scale.x_continuous(minvalue=-0.1, maxvalue=0.1))```

**Comment by aviks** [comment]
This seems to have regressed? Or am I misunderstanding how this works?

![screen shot 2015-01-22 at 11 38 26](https://cloud.githubusercontent.com/assets/378918/5855199/78395426-a22d-11e4-9859-cdcf9eb46c15.png)

**Comment by darwindarak** [comment]
I think the changes introduced [here](https://github.com/dcjones/Gadfly.jl/commit/5ac6b18c32e51fa622f97b827e3d13dac377bda4) to address #252 is overriding the `viewmin/max` aesthetics set in `Scale`.  There are many `min/max` values associated with different aesthetics, and it looks like it is picking the largest value for `viewmax` and smallest value for `viewmin`.

**Comment by aviks** [comment]
Fixed again via #532 by @darwindarak . Thanks!

**Comment by z-m-k** [comment]
This has regressed again.

```Julia
plots(x=1:6500, y=randn(6500), Geom.line, Scale.x_continuous(maxvalue=6500, format=:plain), Stat.xticks(coverage_weight=1.0))
```

Gives range on the x-axis to be 1:7000.
<img width="400" alt="capture" src="https://cloud.githubusercontent.com/assets/3216223/9998401/2a61c60c-6091-11e5-844e-d91a0d33b9e9.PNG">

Without `coverage_weight` (as per #597) the range is 1:8000. In all cases it ignores the explicitly stated `maxvalue`. Maybe a solution would be to set `ticks[end]=minimum([maxvalue, ticks[end]])`? Assuming `ticks` stores the values.

**Comment by mlubin** [comment]
Confirmed broken again

**Comment by timofeymukha** [comment]
I seem to experiece this behaviour too.

**Comment by neilpanchal** [comment]
![image](https://cloud.githubusercontent.com/assets/8161031/15199926/31756800-1797-11e6-9b8c-0547ba60d06b.png)

I am getting weird graphics bug when I export the figures under the Escher.jl framework. I believe it has to do with the `minvalue` and `maxvalue` arguments.

It appears that the `ticks=[90:1:100]` range is conflicting with `Scale.y_continuous(minvalue=90)` in my case. 

I think there is still a bug in the `minvalue` and `maxvalue` arguments. My opinion is to raise and error if ticks are defined outside of the Scale parameters.

For example,

Say, I have a plot with `y=randn(100)` with `Scale.y_continuous(minvalue=40, maxvalue=60)`. 

I shouldnt be able to set ticks=[0:10:100] since it would be misleading. Once the scale is restricted, the user should only be able to set the ticks within that range in my opinion :)

Thank you!
