### ISSUE TITLE
adding layers to existing plots with new mappings

### ISSUE THREAD

**Issue by swadey** [dcjones/Gadfly.jl#52]
Hi,

I managed to add additional gems but not mappings without an error:

```
julia> p = plot(mpg, x = "cty", y = "hwy", Geom.point)
julua> push!(p.layers, layer(Geom.line))
julia> push!(p.layers, layer(x = "displ", Geom.line)) 
ERROR: no method Dict((Symbol,ASCIIString),)
```

**Comment by dehann** [comment]
Hi,

I had to index into the new layer being added to make this work on Julia 0.3.8 and Gadfly 0.3.12, also in IJulia notebook, Ubuntu 12.04.

p = plot(x=linspace(1,10,10), y=rand(10), Geom.line)
push!(p.layers, layer(x=linspace(1,10,10),y=rand(10),Geom.line)[1])

The error without indexing is:

`convert` has no method matching convert(::Type{Layer}, ::Array{Layer,1})

**Comment by dcjones** [comment]
You can actually just say this now:
```julia
push!(p, layer(x=linspace(1,10,10),y=rand(10),Geom.line))
```

**Comment by dehann** [comment]
Thanks Daniel,

Maybe I'm just missing something obvious or on an older version (0.3.8) than you, but I still get this after Pkg.update(). I think the issue is actually with push! itself:

julia> a=[1.0]
julia> push!(a,[2.]) 

ERROR: `convert` has no method matching convert(::Type{Float64}, ::Array{Float64,1})
while loading In[21], in expression starting on line 2

 in push! at array.jl:460

This then is the same problem:

p = plot(x=linspace(1,10,10), y=rand(10), Geom.line)
push!(p.layers, layer(x=linspace(1,10,10),y=rand(10),Geom.line))

`convert` has no method matching convert(::Type{Layer}, ::Array{Layer,1})
while loading In[20], in expression starting on line 2

 in push! at array.jl:460

**Comment by dcjones** [comment]
I hadn't tagged a new version since adding that feature. It should work after doing `Pkg.update()` now.
