### ISSUE TITLE
Odd alignment of dodged bars and additional x axis in grid of subplots with layers

### ISSUE THREAD

**Issue by Treblesteph** [dcjones/Gadfly.jl#528]
This is the original plot, working as I expected:

![original](https://cloud.githubusercontent.com/assets/4573291/5710961/a7325c00-9a9e-11e4-9fcb-e37c3f1b2df9.png)

After updating all my packages, the plot now looks like this:

![new](https://cloud.githubusercontent.com/assets/4573291/5710963/aec60034-9a9e-11e4-9822-e36be0bb077f.png)

Notable problems in the new plot:
- bottom subplot is taller than the others (pushing x axis labels out of view slightly)
- there is an additional x axis
- the bar shading seems to be stretched so that it no longer aligns with the plotted lines

I have tried reverting back to much older versions of Gadfly and Compose and it is still misaligned. It happens both when I use plot, and when I save the plot to a pdf.

The plotting code is [here](https://raw.githubusercontent.com/Treblesteph/network_evo/master/lib/plotOutput.jl), it is quite a complex plot, I am not sure how to make a minimal example of the problem.

**Comment by Treblesteph** [comment]
@dcjones just bumping this issue as I'm blocked by it. Please could you indicate whether this is likely to be a bug in Gadfly or something I am doing wrongly?

**Comment by dcjones** [comment]
Sorry to leave this broken. It's not your fault, the issue is that putting `Geom.subplot_grid` in multiple layers is pretty broken. It will naively draw two subplot grids on top of each other, so they can easily be misaligned. You just happened to get lucky with your original plot, and they were correctly aligned.

The solution will require a little work, but I know roughly what needs to be done, and I'll try to do it later today.

**Comment by dcjones** [comment]
This ended up being trickier that I thought, but it should be possible to do this now. The catch is that you have to use layers within `Geom.subplot_grid` rather than vice versa, like:
```julia
plot1 = plot(Scale.x_continuous(minvalue = 0, maxvalue = 96),
               Scale.y_continuous(minvalue = 0, maxvalue = 1),
          Geom.subplot_grid(
              layer(concframe, x = "time", y = "gene",
                    color = "variable", ygroup = "variable",
                    Geom.line),
              layer(shadeframe, xmin = "starts", xmax = "ends",
                    y = "y", ygroup = "row",
                    Geom.bar(position=:dodge),
                    color = repeat(["dawns", "dusks", "days", "nights"],
                                    outer = [16])),
                    Scale.discrete_color_manual(colourscheme...)))
```

The way you wrote it (subplots in layers), is something that probably should work. I think `plot` should automatically rearrange subplots in layers to layers in a subplot, but need to think about it. For now it will warn about this.
