### ISSUE TITLE
Plot DataFrame with NA

### ISSUE THREAD

**Issue by juliohm** [dcjones/Gadfly.jl#538]
Suppose I have a DataFrame with missing rows. How do I drop all NAs in the spot? I see a function `dropna()` but I'm wondering if Gadfly has a cleaner solution.

```julia
plot(df, x="foo", y="bar", removeNA)?
```

I'm getting an error:

>`convert` has no method matching convert(::Type{Float64}, ::DataArrays.NAtype)

**Comment by juliohm** [comment]
Having a DataFrame with missing rows seems conceptually incorrect from the start. I'm closing the issue.

**Comment by vchuravy** [comment]
For plotting I solve that with defining locally

```
Base.convert(::Type{Float64}, ::DataArrays.NAtype) = NaN
```

, but you wouldn't want such a definition globally.

**Comment by gestay** [comment]
Why is this issue closed? The @vchuravy solution works, but I think Gadfly should handle this.

**Comment by juliohm** [comment]
@gestay I closed the issue because having a DataFrame with missing rows is kind of buggy. Whatever application you have, a missing row doesn`t make much sense, agree? If you have a good counter example, please share. :blush:

**Comment by vchuravy** [comment]
For Gadfly itself, one of the problems I encountered is how to plot data series with gaps, and make these gaps visible. 
Let's say I have two continuous observations, but due to experimental constraints, I am not guaranteed at time `t` to have both  of the observations and I also could have one or none.

If I only have one, I would assign the NA value to the other observation. In that sense it is natural to have NA values in rows and columns of data. The question is if there is a natural way for gadfly to plot NA values.

Another situation are functions with discontinuousness.
