### ISSUE TITLE
Writing plots to multiple PDF pages?

### ISSUE THREAD

**Issue by kshyatt** [dcjones/Gadfly.jl#580]
Is there a way to write all the plots I made to sequential pages of a PDF document, like matplotlib's [PdfPages](http://matplotlib.org/examples/pylab_examples/multipage_pdf.html)? Right now I'm writing out a bunch of plots and collating them after the fact. Can Gadfly do this internally?

**Comment by lobingera** [comment]
Compose.jl contains a backend CAIROSURFACE which uses a pre-defined cairo surface (i know, because i contributed this...) and the cairo PDF surface supports multi-page documents.

So:
```
julia> using Gadfly

julia> p1 = plot(x=rand(10), y=rand(10), Geom.point, Geom.line);

julia> p2 = plot(x=rand(30), y=rand(30), Geom.line);

julia> s = Cairo.CairoPDFSurface("b1.pdf",720.0,300.0);

julia> c = Cairo.CairoContext(s);

julia> b = Compose.CAIROSURFACE(s);

julia> draw(b,p1);

julia> Cairo.show_page(c);

julia> draw(b,p2);

julia> Cairo.finish(s)
```

works for me at the REPL. 

The command to advance a page is the Cairo.show_page(c) with c the CairoContext of the surface. In theory this can be written shorter, because the Compose backend should contain both the surface and context, but i ran into problems. So here the long form.

**Comment by kshyatt** [comment]
Thanks so much! This solves this for me.

**Comment by ultradian** [comment]
I am using Julia 0.4 and when I try this, I get the error:

>ERROR: The backend has already been drawn upon.
 in draw at /home/emo/.julia/v0.4/Compose/src/container.jl:431
 in draw at /home/emo/.julia/v0.4/Gadfly/src/Gadfly.jl:842

when I try to call draw the second time
>julia> draw(b,p2);

Any suggestions on getting around this?

**Comment by lobingera** [comment]
Not without looking into the details. Compose had some restructuring and there might be a reason, why you can only draw once on a Backend.

**Comment by rohitvarkey** [comment]
https://github.com/dcjones/Compose.jl/pull/170 is the reason for this.

**Comment by lobingera** [comment]
I saw this also, but this only a workaround, not solving the segmentation fault

**Comment by lobingera** [comment]
i do not consider this a solution, but you can 'unfinish' a img/backend by (re-)setting the flag manually
```
julia> b.finished = false;
```
and then it works (for me) like previously.
