### ISSUE TITLE
Very slow plotting and drawing (> 5 hrs)

### ISSUE THREAD

**Issue by GravityAssisted** [dcjones/Gadfly.jl#649]
Hi all,

I am trying to create a subplot (square grid) of out of a large DataFrame object (8016878, 29). It took more than 5 hrs (!) to make the plot and another 3.5+ hrs to draw it !
I wanted to ask why is there such a huge performance hit. Is there something I am doing wrong in my code below ? 
I saw (via the linux Top command) that julia has allocated ~ 20 GB of data to VIRT memory and 0.016 terabyte to RES. This seems unusually high. 
The command I am using to make the subplot is as follows:
```julia
set_default_plot_size( 9inch, 3.6inch)

myplot =plot(Results,x="Escape_Vinf",y="TOF", color="NumFlyby", xgroup="KBO", Geom.subplot_grid(Geom.point), Guide.colorkey("# Flybys "),  Guide.xlabel("Escape Velocity (au/yr.)"),Guide.ylabel("TOF (yrs.)"),Theme(default_point_size=0.3mm,highlight_width=0.01mm, minor_label_font_size=11pt, background_color=color("white"), colorkey_swatch_shape=:circle, guide_title_position=:left ))

draw(PNG("Output.png",  9inch, 3.6inch, dpi=300),myplot);
```
I would really appreciate any advice on speeding up the plotting or if there is any clever way to improve it ?

I am on Julia 0.3.xx and latest stable version of Gadfly.
thanks a lot.

**Comment by timholy** [comment]
Others who know Gadfly better than I may have specific suggestions, but in general I'd suggest [profiling](http://docs.julialang.org/en/release-0.3/manual/profile/) any time you have performance questions. ProfileView.jl gives you a nice way of viewing the results, and you can even post the results as an SVG file or IJulia notebook so that others (who might know more about Gadfly's internals) can browse the results.

It will take a few minutes to learn how to use these tools, but my experience has been that learning to use the profiler is the fastest route to learning how to write efficient julia code (i.e., it will have long-lasting benefits for you).

I'd recommend profiling on a small subset of your DataFrame; if you really have to do the full 5 hours, then you should definitely set `Profile.init(delay=0.1,n=10^7)` or something (otherwise you will fill up the profiling buffer in the first 20s or so).

**Comment by dcjones** [comment]
The call the `plot` took 5 hours? That's really peculiar. I tried to reproduce it by generating 8 million rows of random data. The `plot` call took 0.85 seconds and `draw` took about 9 minutes. That's still quite slow, but nothing like what you got.

What are the types of the columns, and how many unique values are there in `KBO`? Also, is it possible that you're out of memory and it's swapping? It does allocate a lot.

**Comment by lobingera** [comment]
Same here, i tried to plot 10mio data and had similar times like Daniel. 
@GravityAssisted, can you somehow tell us more about the data and your computer. Even 20G for holding the data is strange.

**Comment by GravityAssisted** [comment]
Thanks all for the replies. 

My computer is a very capable machine with 12 cores, 32 GB of RAM and 512GB SSD. I don't think I am running out of memory or RAM.

The original Dataframe is a huge one with 8016878 rows and 29 columns. Some of the columns have text (long ASCII strings) and some are floating point (Float64) numbers. The Dataframe itself in .csv format takes couple+ of gigabytes of storage space.

I didn't had the chance to profile (maybe tonight I will) but I did notice a little improvement by removing the columns I don't need in my dataframe (I only need like 10, with only 2 of them being strings). I am also currently trying to move to Julia-0.4 and it does seem to give me a performance boost. Its running as we speak so lets see how fast it can be. I will update again.

Finally in Julia-0.4 Gadfly is having another issue of drawing to PNG back end as it complains about installation of Cairo (which I already have). I was able to overcome this by drawing to SVG and converting using Imagmagick.

thanks
